send_anonymous_usage_stats: false
Hackathon:
    target: Snowflake_DB
    outputs:
        Snowflake_DB:
            type: snowflake
            account: [account id]
            user: [username]
            password: [password]
            database: [database name]
            warehouse: [warehouse name]
            schema: [dbt schema]
